### ISSUE TITLE
Commit 3e2582caa causes error 'E118: Too many arguments for function: s:MkdirCallable'

### ISSUE THREAD

**Issue by andrewferrier** [tpope/vim-eunuch#91]
Since commit 3e2582caa (I have confirmed this with `git bisect`), vim shows:

    E118: Too many arguments for function: s:MkdirCallable
    E116: Invalid arguments for function call

When trying to rename a file with `:Rename`. It also doesn't rename the file.

I haven't found any workaround for the issue. `:Move` seems to be broken too.

Regressing to the previous commit resolves the issue.

I'm on NVIM v0.8.0-dev+9-g1facad234, in case it's important.

**Comment by tpope** [comment]
Thanks for the heads up.
